version: "3"
services:
  db:
    image: postgres
    container_name: yt_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
  encoding-service:
    build:
      context: ./encoding/.
    container_name: encoding_service
    working_dir: /app
    restart: unless-stopped
    ports:
      - 3000:3000
  