version: "3"
services:
  db:
    image: postgres
    container_name: yt_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
  # uploading-service:
  #   build:
  #     context: ./uploading/.
  #   container_name: encoding_service
  #   depends_on:
  #     - minio-service
  #     - db
  #   working_dir: /app
  #   restart: unless-stopped
  #   command: yarn start
  #   ports:
  #     - 3000:3000
  minio-service:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9099:9099
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_SERVER_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SERVER_SECRET_KEY}
    command: server --address ":9099" --console-address ":9000" /data
  abbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
  # mc-service:
  #   image: minio/mc:latest
  #   depends_on:
  #     - minio-service
  #   entrypoint: >
  #     /bin/sh -c " /usr/bin/mc alias set myminio http://minio-container:9000 ${MINIO_SERVER_ACCESS_KEY} ${MINIO_SERVER_SECRET_KEY}; /usr/bin/mc mb myminio/mybucket; /usr/bin/mc policy set public myminio/mybucket; "
